services:
  proxy:
    image: ghcr.io/fishhawk/wneg-proxy
    ports:
      - 80:80
    volumes:
      - ${DATA_PATH}/files-web:/data/files-web
      - ${DATA_PATH}/files-wenku:/data/files-wenku
      - ${DATA_PATH}/files-extra:/data/files-extra
    restart: always

  server:
    image: ghcr.io/fishhawk/wneg-server
    depends_on:
      - mongo
    environment:
      - HTTPS_PROXY
      - EMAIL_PASSWORD
      - JWT_SECRET
      - PIXIV_COOKIE_PHPSESSID
      - MONGODB_URL=mongodb://mongo:27017
      - ELASTIC_SEARCH_DB_URL=elasticsearch
      - REDIS_URL=redis:6379
    ports:
      - 8081:8081
    volumes:
      - ${DATA_PATH}/files-web:/data/files-web
      - ${DATA_PATH}/files-wenku:/data/files-wenku
      - ${DATA_PATH}/files-extra:/data/files-extra
    restart: always

  mongo:
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_DATABASE=auth
    ports:
      - 27017:27017
    volumes:
      - ${DATA_PATH}/db:/data/db
    restart: always

  elasticsearch:
    image: elasticsearch:8.6.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ${DATA_PATH}/es/data:/usr/share/elasticsearch/data
      - ${DATA_PATH}/es/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    restart: always

  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379
    restart: always